project_id = "uccblgllyezbfsubfqin"

[functions.initiate-paytech-payment]
verify_jwt = true

[functions.verify-paytech-payment]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.generate-estimation-pdf]
verify_jwt = false

[functions.generate-article]
verify_jwt = true